### ISSUE TITLE
Unnecessary check for thisArg

### ISSUE THREAD

**Issue by AlexYalovoy** [RuQuentin/tests_MyArray#22]
https://github.com/RuQuentin/tests_MyArray/blob/e778c8e98d9cfcc250247b7cc68938ee8902f603/src/index.js#L87

**Comment by RuQuentin** [comment]
You know, we discussed it already and I agreed with you.
But then I thought one more and came to decision that we may not need to have undefined by default. It depends on which mode we use.
In a 'strict mode' it should return undefined. Without it - window.
So, I would probably leave this line, and in this case a value of this will depend on which mode you use.
So, what's your opinion about it?

Actually, Andrey (whose code I reviewed) proposed an interesting solution - to set default value in arguments list like this: function( cb, thisArg = this). But I want to check if it works in all the cases.

**Comment by AlexYalovoy** [comment]
Maybe you are right about strict mode. But I can't say how it should be realized. We need to ask Timiphey about that to have no doubdt.
