### ISSUE TITLE
Unnecessary if construction. Set default value to empty string.

### ISSUE THREAD

**Issue by AlexYalovoy** [RuQuentin/tests_MyArray#25]
https://github.com/RuQuentin/tests_MyArray/blob/e778c8e98d9cfcc250247b7cc68938ee8902f603/src/index.js#L210

**Comment by RuQuentin** [comment]
I'm not sure that it can help. If I don't use IF here - I'll need it later with my FOR. But I try to avoid FOR insede IF or another multilevel constructions if it's possible.
Do you see the way to do it without IF at all?
